# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5V0HdyzsnbpWhsGnFMfEoQiucxFotwq

### NPS USE CASE

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">
"""

!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

import numpy as np

scores = np.loadtxt('survey.txt',dtype='int')
scores

scores.ndim

scores.shape

len(scores)

#first 10 scores
scores[:10]

#nps score ? = promoters , detractors
#promoters
promoters = scores[scores>8]
len(promoters)

#detractors
detractors = scores[scores < 7]
len(detractors)

#nps score
nps = 100 * (len(promoters) - len(detractors))/ len(scores)
nps

round(nps,2)

"""#working with 2d arrays"""

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

a.ndim

a.shape

#total no of elemenst
len(a) #no. of 1d arrays

#total elements
a.size

"""# 2d arrays from 1d array"""

a = np.arange(1,13)
a

a.ndim

a.shape

len(a)

a.size

a

#reshape
a.reshape(4,4)

a.reshape(4,3)

a.reshape(3,4)

a.reshape(2,6)

a.reshape(6,2)

a

a.reshape(1,12)

a.reshape(12,1)

a.reshape(3,-1)

a.reshape(-1,6)

a.reshape(-1,-1)

a.reshape(-1,)

#transpose of the matrix

a = np.arange(1,13)
b = a.reshape(3,4)
b

b.T #giving the new array

b.T.shape

b

#2d array to 1 array

b

b.flatten()

b.flatten().shape

#indexing on 2d arrays
m1 = np.arange(1,10).reshape(3,3)
m1

m1[1][1]

m1[1,1] #alternative way

m1[2,0]

#can i multiple indexes
a = np.array([100,200,300,400,500,600])
a[[0,1,1,3,2,4]]

m1

m1[[0,1,2],[0,1,2]]

#slicing

m1

m1[:2] #row indices

m1[:,:]

m1[:,:2]

m1 = np.arange(1,13).reshape(3,4)
m1

m1[1:3,1:3]

m1[:,1:4:2]

m1[:,[1,3]] #alternative way

#quiz
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
print(a)

m1

#masking on 2d arrays
m1 < 6

m1[m1< 6]

m1[m1%3==0]

#sum , min , max , mean

m1

a = np.arange(1,11)
a

np.sum(a)

a.size

np.mean(a)

np.min(a)

print(np.max(a))

print(np.median(a))

help(np)

m1

np.median?

print(np.sum(m1))

m1

np.sum?

np.sum(m1,axis = 1) #horizontal

np.sum(m1,axis=0) #vertical

m1

np.min(m1)

np.min(m1,axis=0)

!pip install numpy
import numpy as np